name: pixelenv
channels:
  - conda-forge
dependencies:
  - python = 3.7.5
  - requests = 2.22.0
  - sqlparse = 0.3.0
  - django = 2.2.5
  - yapf = 0.28.0
  - psycopg2 = 2.8.4
  - django-extensions = 2.2.1
  - Werkzeug = 0.16.0
  - pyOpenSSL = 19.0.0
  - pillow = 6.2.1
